services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security_monitor
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d security_monitor"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  gateway:
    build: ./gateway
#   environment:
#     DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
    ports:
      - "8080:8080"
    networks:
      - microservices-net

  events-backend-1:
    build: ./events-backend
    environment:
      INSTANCE_ID: events-1
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  events-backend-2:
    build: ./events-backend
    environment:
      INSTANCE_ID: events-2
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  events-backend-3:
    build: ./events-backend
    environment:
      INSTANCE_ID: events-3
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  detection-backend-1:
    build: ./detection-backend
    environment:
      INSTANCE_ID: detection-1
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  detection-backend-2:
    build: ./detection-backend
    environment:
      INSTANCE_ID: detection-2
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  detection-backend-3:
    build: ./detection-backend
    environment:
      INSTANCE_ID: detection-3
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net
  
  incidents-backend-1:
    build: ./incidents-backend
    environment:
      INSTANCE_ID: incidents-1
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  incidents-backend-2:
    build: ./incidents-backend
    environment:
      INSTANCE_ID: incidents-2
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

  incidents-backend-3:
    build: ./incidents-backend
    environment:
      INSTANCE_ID: incidents-3
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=security_monitor sslmode=disable"
  # ports:
  #  - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net

volumes:
  postgres_data:

networks:
  microservices-net:
    driver: bridge